force-app/main/default/objects/Certificaci_n__c/Certificaci_n__c.object-meta.xml
<CustomObject>
    <label>Certificación</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificaci_n__c/fields/Certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Certificaci_n__c</fullName>
    <label>Certificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_certificaci_n__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Miembro_de_la_cohorte__c.field-meta.xml
<CustomField>
    <fullName>Miembro_de_la_cohorte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Miembro de la cohorte</label>
    <referenceTo>Miembro_de_la_cohorte__c</referenceTo>
    <relationshipLabel>Certificaciones</relationshipLabel>
    <relationshipName>Certificaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Tipo_de_certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_certificaci_n__c</fullName>
    <label>Tipo de certificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cohorte__c/Cohorte__c.object-meta.xml
<CustomObject>
    <label>Cohorte</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Número de cohorte</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohortes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cohorte__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Módulo</label>
    <referenceTo>M_dulo__c</referenceTo>
    <relationshipLabel>Cohortes</relationshipLabel>
    <relationshipName>Cohortes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/M_dulo__c/M_dulo__c.object-meta.xml
<CustomObject>
    <label>Módulo</label>
    <nameField>
        <label>Nombre de Módulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Módulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/M_dulo__c/fields/Certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Certificaci_n__c</fullName>
    <label>Certificación</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_certificaci_n__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Miembro_de_la_cohorte__c/Miembro_de_la_cohorte__c.object-meta.xml
<CustomObject>
    <description>Objeto junction entre contacto y cohorte</description>
    <label>Miembro de la cohorte</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Nombre de Miembro de la cohorte</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miembros de la cohorte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Miembro_de_la_cohorte__c/fields/Cohorte__c.field-meta.xml
<CustomField>
    <fullName>Cohorte__c</fullName>
    <description>Cohorte que contendra a los empleados</description>
    <label>Cohorte</label>
    <referenceTo>Cohorte__c</referenceTo>
    <relationshipLabel>Miembros de la cohorte</relationshipLabel>
    <relationshipName>Miembros_de_la_cohorte</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resultado_de_secci_n__c/Resultado_de_secci_n__c.object-meta.xml
<CustomObject>
    <label>Resultado de sección</label>
    <nameField>
        <displayFormat>Sec-{000}</displayFormat>
        <label>Nombre de Sección</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resultados de secciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resultado_de_secci_n__c/fields/Certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Certificaci_n__c</fullName>
    <label>Certificación</label>
    <referenceTo>Intento_de_certificacion__c</referenceTo>
    <relationshipLabel>Resultados de secciones</relationshipLabel>
    <relationshipName>Resultados_de_secciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resultado_de_secci_n__c/fields/nombre_de_seccion__c.field-meta.xml
<CustomField>
    <fullName>nombre_de_seccion__c</fullName>
    <formula>Secciones_de_certificaci_n__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>nombre de seccion</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Certificaci_n.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Application Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Solution Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Solution Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architect</fullName>
    </customValue>
    <customValue>
        <fullName>System Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Industries CPQ Developer</fullName>
    </customValue>
    <customValue>
        <fullName>JavaScript Developer I</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Developer</fullName>
    </customValue>
    <customValue>
        <fullName>OmniStudio Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Platform App Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Developer I</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Developer II</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Email Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Education Cloud Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Experience Cloud Consultant</fullName>
    </customValue>
    <masterLabel>Certificación</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_de_certificaci_n.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Marketer</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Designer</fullName>
    </customValue>
    <masterLabel>Tipo de certificación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Certificacion.cls
public with sharing class Certificacion {
    
    // se obtiene el tipo de certificacion y certificacion al que esta asociado el miembro de la cohorte
    @AuraEnabled(cacheable = true)
    public static certiWrapper obtenerModulo(string miembroId) {
        Miembro_de_la_cohorte__c miembro = [SELECT id, Name, Cohorte__c FROM Miembro_de_la_cohorte__c WHERE Id =:miembroId LIMIT 1];
        Cohorte__c cohorte = [SELECT Id, Name, Modulo__c FROM Cohorte__c WHERE id =:miembro.Cohorte__c LIMIT 1];
        M_dulo__c modulo = [SELECT id, Name, Certificaci_n__c, Tipo_de_certificaci_n__c FROM M_dulo__c WHERE id =:cohorte.Modulo__c LIMIT 1];
        certiWrapper resultado = new certiWrapper(modulo.Tipo_de_certificaci_n__c, modulo.Certificaci_n__c);
        return resultado;
    }

    // se obtienen todas las secciones segun el certificado salesforce registrado
    @AuraEnabled(cacheable = true)
    public static List<Resultado_de_secci_n__c> getSecciones(string certificado){
        return [
            SELECT id, Certificaci_n__c, nombre_de_seccion__c, Resultado__c
            FROM Resultado_de_secci_n__c
            WHERE Certificaci_n__c =: certificado
        ];
    }

    // wraper para regresar la infomacion obtenida en el modulo
    public class certiWrapper{
        @AuraEnabled
        public string tipoCertificacion;
        @AuraEnabled
        public string certificacion;

        public certiWrapper(string tipoCertifi, string certifi){
            this.tipoCertificacion = tipoCertifi;
            this.certificacion = certifi;
        }
    }
}