force-app/main/default/objects/Certificaci_n__c/Certificaci_n__c.object-meta.xml
<CustomObject>
    <label>Certificación</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificaci_n__c/fields/Certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Certificaci_n__c</fullName>
    <label>Certificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_certificaci_n__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intento_de_certificacion__c/Intento_de_certificacion__c.object-meta.xml
<CustomObject>
    <label>Intento de certificación</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intentos de certificación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Certificaci_n.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Application Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Solution Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Solution Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architect</fullName>
    </customValue>
    <customValue>
        <fullName>System Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Industries CPQ Developer</fullName>
    </customValue>
    <customValue>
        <fullName>JavaScript Developer I</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Developer</fullName>
    </customValue>
    <customValue>
        <fullName>OmniStudio Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Platform App Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Developer I</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Developer II</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Email Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Education Cloud Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Experience Cloud Consultant</fullName>
    </customValue>
    <masterLabel>Certificación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntentoDeCertificacionTriggerHandler.cls
public with sharing class IntentoDeCertificacionTriggerHandler implements TriggerHandler{
    private boolean triggerIsExecuting;
    private integer triggerSize;
    public IntentoDeCertificacionTriggerHandler(boolean triggerIsExecuting, integer triggerSize) {
        this.triggerIsExecuting = triggerIsExecuting;
        this.triggerSize = triggerSize;
    }

    public void beforeInsert(List<Intento_de_certificacion__c> newRecords) {
        actualizarNombreIntento(newRecords);
    }
    public void beforeUpdate(List<Intento_de_certificacion__c> oldRecords, List<Intento_de_certificacion__c> newRecords, Map<ID, sObject> oldRecordMap, Map<ID, sObject> newRecordMap){
        actualizarNombreIntento(newRecords);
    }
    public void beforeDelete(List<Intento_de_certificacion__c> oldRecords, Map<ID, sObject> oldRecordMap) {

    }
    public void afterInsert(List<Intento_de_certificacion__c> newRecords, Map<ID, sObject> newRecordMap) {

    }
    public void afterUpdate(List<Intento_de_certificacion__c> oldRecords, List<Intento_de_certificacion__c> newRecords, Map<ID, sObject> oldRecordMap, Map<ID, sObject> newRecordMap) {
        
    }
    public void afterDelete(List<Intento_de_certificacion__c> oldRecords, Map<ID, sObject> oldRecordMap) {

    }
    public void afterUndelete(List<Intento_de_certificacion__c> newRecords, Map<ID, sObject> newRecordMap) {

    }

    public static void actualizarNombreIntento(List<Intento_de_certificacion__c> intentos) {

        for (Intento_de_certificacion__c intento : intentos) {
            intento.Name = intento.Certificaci_n__c;
        }    
    }

}