force-app/main/default/objects/Certificaci_n__c/Certificaci_n__c.object-meta.xml
<CustomObject>
    <label>Certificación</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificaci_n__c/fields/Aprueba__c.field-meta.xml
<CustomField>
    <fullName>Aprueba__c</fullName>
    <defaultValue>false</defaultValue>
    <description>determina si fue aprobado el intento de certificacion</description>
    <label>Aprueba</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Certificaci_n__c</fullName>
    <label>Certificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_certificaci_n__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Miembro_de_la_cohorte__c.field-meta.xml
<CustomField>
    <fullName>Miembro_de_la_cohorte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Miembro de la cohorte</label>
    <referenceTo>Miembro_de_la_cohorte__c</referenceTo>
    <relationshipLabel>Certificaciones</relationshipLabel>
    <relationshipName>Certificaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Certificaci_n__c/fields/Tipo_de_certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_certificaci_n__c</fullName>
    <label>Tipo de certificación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certificaciones_Salesforce__c/Certificaciones_Salesforce__c.object-meta.xml
<CustomObject>
    <label>Certificaciones Salesforce</label>
    <nameField>
        <label>Nombre de Certificación Salesforce</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificaciones Salesforce</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cohorte__c/Cohorte__c.object-meta.xml
<CustomObject>
    <label>Cohorte</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Número de cohorte</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohortes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cohorte__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <label>Fecha de inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cohorte__c/fields/Intentos_de_certificacion_permitidos__c.field-meta.xml
<CustomField>
    <fullName>Intentos_de_certificacion_permitidos__c</fullName>
    <label>Intentos de certificación permitidos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cohorte__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Módulo</label>
    <referenceTo>M_dulo__c</referenceTo>
    <relationshipLabel>Cohortes</relationshipLabel>
    <relationshipName>Cohortes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha en la que inicio en la empresa que registro como experiencia laboral</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Habilidad__c/Habilidad__c.object-meta.xml
<CustomObject>
    <description>Capacidad, disposicion o conocimiento de algo</description>
    <label>Habilidad</label>
    <nameField>
        <label>Nombre de Habilidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Intento_de_certificacion__c/Intento_de_certificacion__c.object-meta.xml
<CustomObject>
    <label>Intento de certificación</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intentos de certificación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Intento_de_certificacion__c/fields/Aprueba__c.field-meta.xml
<CustomField>
    <fullName>Aprueba__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprueba</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Intento_de_certificacion__c/fields/Certificaciones_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Certificaciones_Salesforce__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificaciones Salesforce</label>
    <referenceTo>Certificaciones_Salesforce__c</referenceTo>
    <relationshipName>Certificaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Intento_de_certificacion__c/fields/Miembro_de_la_cohorte__c.field-meta.xml
<CustomField>
    <fullName>Miembro_de_la_cohorte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Miembro de la cohorte</label>
    <referenceTo>Miembro_de_la_cohorte__c</referenceTo>
    <relationshipName>Certificaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Intento_de_certificacion__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Intento_de_certificacion__c/fields/Tipo_de_certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_certificaci_n__c</fullName>
    <label>Tipo de certificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intento_de_certificacion__c/fields/Tipo_de_intento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_intento__c</fullName>
    <label>Tipo de intento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certificación</fullName>
            </value>
            <value>
                <fullName>Simulacro de certificación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/M_dulo__c/M_dulo__c.object-meta.xml
<CustomObject>
    <label>Módulo</label>
    <nameField>
        <label>Nombre de Módulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Módulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/M_dulo__c/fields/Certificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Certificaci_n__c</fullName>
    <label>Certificación</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_certificaci_n__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Certificaci_n</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/M_dulo__c/fields/Intentos_de_certificacion_permitidos__c.field-meta.xml
<CustomField>
    <fullName>Intentos_de_certificacion_permitidos__c</fullName>
    <label>Intentos de certificación permitidos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Miembro_de_la_cohorte__c/Miembro_de_la_cohorte__c.object-meta.xml
<CustomObject>
    <description>Objeto junction entre contacto y cohorte</description>
    <label>Miembro de la cohorte</label>
    <nameField>
        <displayFormat>MC-{0000}</displayFormat>
        <label>Nombre de Miembro de la cohorte</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Miembros de la cohorte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Miembro_de_la_cohorte__c/fields/Cohorte__c.field-meta.xml
<CustomField>
    <fullName>Cohorte__c</fullName>
    <description>Cohorte que contendra a los empleados</description>
    <label>Cohorte</label>
    <referenceTo>Cohorte__c</referenceTo>
    <relationshipLabel>Miembros de la cohorte</relationshipLabel>
    <relationshipName>Miembros_de_la_cohorte</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Miembro_de_la_cohorte__c/fields/Empleado__c.field-meta.xml
<CustomField>
    <fullName>Empleado__c</fullName>
    <description>Empleado que hace parte de una cohorte</description>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado Salesforce</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Miembros de la cohorte</relationshipLabel>
    <relationshipName>Miembros_de_la_cohorte</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/secciones_de_certificacion__c/secciones_de_certificacion__c.object-meta.xml
<CustomObject>
    <label>Secciones de certificación</label>
    <nameField>
        <label>Sección de certificación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secciones de certificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/secciones_de_certificacion__c/fields/Certificaciones_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Certificaciones_Salesforce__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificaciones Salesforce</label>
    <referenceTo>Certificaciones_Salesforce__c</referenceTo>
    <relationshipLabel>Secciones de certificaciones</relationshipLabel>
    <relationshipName>Secciones_de_certificaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Certificaci_n.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>CPQ Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Application Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Solution Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Solution Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Heroku Architect</fullName>
    </customValue>
    <customValue>
        <fullName>System Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Development Lifecycle and Deployment Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Identity and Access Management Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Integration Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Data Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Sharing and Visibility Architect</fullName>
    </customValue>
    <customValue>
        <fullName>B2C Commerce Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Industries CPQ Developer</fullName>
    </customValue>
    <customValue>
        <fullName>JavaScript Developer I</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Developer</fullName>
    </customValue>
    <customValue>
        <fullName>OmniStudio Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Platform App Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Developer I</fullName>
    </customValue>
    <customValue>
        <fullName>Platform Developer II</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud Email Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Pardot Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Education Cloud Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Experience Cloud Consultant</fullName>
    </customValue>
    <masterLabel>Certificación</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_de_certificaci_n.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Marketer</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Designer</fullName>
    </customValue>
    <masterLabel>Tipo de certificación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntentoCertificacionTriggerHandlerTest.cls
@isTest
public class IntentoCertificacionTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        Habilidad__c habilidad = new Habilidad__c(Name = 'Administrator');
        insert habilidad;
        
        List<Contact> contactos = new List<Contact>();
        for(Integer i = 0; i < 10; i++){
            Contact nuevoContacto = new Contact(LastName = 'Prueba' + i, RecordTypeId = '012Dn0000006c0RIAQ');
            contactos.add(nuevoContacto);
        }
        insert contactos;
        
        M_dulo__c modulo = new M_dulo__c(Intentos_de_certificacion_permitidos__c = 3, Name= 'Administrator', Certificaci_n__c = 'Administrator', Tipo_de_certificaci_n__c = 'Administrator');
        insert modulo;
        
        Cohorte__c cohorte = new Cohorte__c(Fecha_de_inicio__c= Date.newInstance(2023, 02, 15), Modulo__c = modulo.Id);
        insert cohorte;
        
        List<Miembro_de_la_cohorte__c> miembrosCohorte = new List<Miembro_de_la_cohorte__c>();
       	for(Contact contacto : contactos){
            Miembro_de_la_cohorte__c miembroCohorte = new Miembro_de_la_cohorte__c(Cohorte__c = cohorte.Id, Empleado__c = contacto.Id);
            miembrosCohorte.add(miembroCohorte);
        }
        
        insert miembrosCohorte;
        
        Certificaciones_Salesforce__c certSf = new Certificaciones_Salesforce__c(Name = 'Administrator');
        insert certSf;

        List<secciones_de_certificacion__c> secciones = new List<secciones_de_certificacion__c>();
        secciones.add(new secciones_de_certificacion__c(Name = 'Configuration and Setup',Certificaciones_Salesforce__c = certSf.Id));
        secciones.add(new secciones_de_certificacion__c(Name = 'Sales and Marketing Applications',Certificaciones_Salesforce__c = certSf.Id));
        secciones.add(new secciones_de_certificacion__c(Name = 'Object Manager and Lightning App Builder',Certificaciones_Salesforce__c = certSf.Id));
        secciones.add(new secciones_de_certificacion__c(Name = 'Workflow/Process Automation',Certificaciones_Salesforce__c = certSf.Id));
        secciones.add(new secciones_de_certificacion__c(Name = 'Service and Support Applications',Certificaciones_Salesforce__c = certSf.Id));
        secciones.add(new secciones_de_certificacion__c(Name = 'Productivity and Collaboration',Certificaciones_Salesforce__c = certSf.Id));
        secciones.add(new secciones_de_certificacion__c(Name = 'Data and analytics management',Certificaciones_Salesforce__c = certSf.Id));
        insert secciones;
        
        List<Intento_de_certificacion__c> certificaciones = new List<Intento_de_certificacion__c>();
        for(Miembro_de_la_cohorte__c miembroCoh :  miembrosCohorte){
            Intento_de_certificacion__c certificacion = new Intento_de_certificacion__c( Aprueba__c= true, Certificaciones_Salesforce__c = certSf.Id, Miembro_de_la_cohorte__c = miembroCoh.Id, Tipo_de_intento__c= 'Certificación');
            certificaciones.add(certificacion);
        }
        insert certificaciones;
    }

    @isTest
    public static void updateName(){
        Intento_de_certificacion__c certificacion = [SELECT ID, name, Certificaciones_Salesforce__c FROM Intento_de_certificacion__c LIMIT 1];
        /* IntentoDeCertificacionTriggerHandler resultado = new IntentoDeCertificacionTriggerHandler.actualizarNombreIntento(certificacion); */
        System.assertEquals('Administrator', certificacion.name);
    }
    
    @isTest
    public static void impedirCertDoble(){
        try{
            List<Miembro_de_la_cohorte__c> miembrosCohorte = [SELECT Id FROM Miembro_de_la_cohorte__c];
            Certificaciones_Salesforce__c certSf = [SELECT Id FROM Certificaciones_Salesforce__c LIMIT 1];
            List<Intento_de_certificacion__c> certificaciones = new List<Intento_de_certificacion__c>();
            for(Miembro_de_la_cohorte__c miembroCoh :  miembrosCohorte){
                Intento_de_certificacion__c certificacion = new Intento_de_certificacion__c( Aprueba__c= true, Certificaciones_Salesforce__c = certSf.Id, Miembro_de_la_cohorte__c = miembroCoh.Id, Name = 'Administrator', Tipo_de_intento__c= 'Certificación');
                certificaciones.add(certificacion);
            }
            insert certificaciones;
            
        }catch(Exception e){
            System.assert(e.getMessage().contains('La certificación que intenta agregar ya fue aprobada por el miembro de la cohorte'));
        }

    }
    
    @isTest
    public static void eliminarCert(){
        List<Intento_de_certificacion__c> listaCert = [SELECT Id FROM Intento_de_certificacion__c];
        List<Intento_de_certificacion__c> undeleteCert = new List<Intento_de_certificacion__c>();
        for(Intento_de_certificacion__c intento: listaCert){
            Intento_de_certificacion__c recuperaCert = new Intento_de_certificacion__c(Id = intento.Id);
            undeleteCert.add(recuperaCert);
        }
        delete listaCert;
        List<Intento_de_certificacion__c> listaElim = [SELECT Id FROM Intento_de_certificacion__c];
        System.assertEquals(0, listaElim.size());
        undelete undeleteCert;
        List<Intento_de_certificacion__c> listaRec = [SELECT Id FROM Intento_de_certificacion__c];
        System.assertEquals(10, listaRec.size());
    }
    
    @isTest
    public static void actualizarCert(){
        List<Intento_de_certificacion__c> listaCert = [SELECT Id FROM Intento_de_certificacion__c];
        List<Intento_de_certificacion__c> actualizarCert = new List<Intento_de_certificacion__c>();
        for(Intento_de_certificacion__c intento: listaCert){
            Intento_de_certificacion__c ActCert = new Intento_de_certificacion__c(Id= intento.Id ,Resultado__c = 76);
            actualizarCert.add(ActCert);
        }
        
        update actualizarCert;
       	List<Intento_de_certificacion__c> resultado = [SELECT Id FROM Intento_de_certificacion__c WHERE Resultado__c = 76];
        system.assertEquals(10, resultado.size());
    }
}