force-app/main/default/objects/Novedad__c/Novedad__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa las novedades que puede presentar un empleado, como incapacidad, vacaciones, licencia, en labor, otra.</description>
    <label>Novedad</label>
    <nameField>
        <displayFormat>NV-{0000}</displayFormat>
        <label>Nombre de Novedad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Novedades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Novedad__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la novedad esta activa o no</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Empleado__c.field-meta.xml
<CustomField>
    <fullName>Empleado__c</fullName>
    <description>Empleado que tendrá asociadas las novedades</description>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado Salesforce, Empleado E-volution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Novedades</relationshipLabel>
    <relationshipName>Novedades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_finalizacion__c</fullName>
    <description>Fecha de finalización de la novedad</description>
    <label>Fecha de finalización</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio de la novedad</description>
    <label>Fecha de inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Jornada__c.field-meta.xml
<CustomField>
    <fullName>Jornada__c</fullName>
    <description>Define la jornada de la asignacion laboral en tiempo completo, medio tiempo AM, medio tiempo PM con el fin de realizar un mejor seguimiento</description>
    <label>Jornada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tiempo Completo</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Tipo_de_novedad__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_novedad__c</fullName>
    <description>Tipo de novedades que se pueden presentar</description>
    <label>Tipo de novedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incapacidad</fullName>
            </value>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Licencia</fullName>
            </value>
            <value>
                <fullName>Otra</fullName>
            </value>
            <value>
                <fullName>Asignacion Laboral</fullName>
                <label>Asignación Laboral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/schedulableNovedad.cls
public class schedulableNovedad implements Schedulable{
    
    public void execute(SchedulableContext ctx){
        List<Novedad__c> novedades = [select id, Empleado__c , Tipo_de_novedad__c, Jornada__c, Activo__c , Fecha_de_inicio__c, Fecha_de_finalizacion__c   from Novedad__c ];
        list<Novedad__c> novedadesActualizables= new list<Novedad__c>();
        
        for(Novedad__c novedad: novedades){
            if(date.today() <= novedad.Fecha_de_finalizacion__c && date.today() >= novedad.Fecha_de_inicio__c && novedad.Activo__c != true){
                novedad__c nuevaNovedad = new novedad__C();
                nuevaNovedad.Id = novedad.Id;
                nuevaNovedad.Activo__c = true;
                novedadesActualizables.add(nuevaNovedad);
            }else if(date.today() <= novedad.Fecha_de_finalizacion__c && date.today() >= novedad.Fecha_de_inicio__c && novedad.Activo__c != false){
                
            }else{
                novedad__c nuevaNovedad = new novedad__C();
                nuevaNovedad.Id = novedad.Id;
                nuevaNovedad.Activo__c = false;
                novedadesActualizables.add(nuevaNovedad);
            }
        }
        try{
            update novedadesActualizables;
        }catch(exception e){
            throw new ErrorException(e);
        }
        
    }
    
    public class ErrorException extends Exception{}
}