force-app/main/default/objects/Contact/fields/Disponibilidad__c.field-meta.xml
<CustomField>
    <fullName>Disponibilidad__c</fullName>
    <description>especifica la disponibilidad de este empleado para una asignacion laboral</description>
    <label>Disponibilidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponible</fullName>
            </value>
            <value>
                <fullName>No Disponible</fullName>
            </value>
            <value>
                <fullName>Disponible Medio Tiempo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha en la que inicio en la empresa que registro como experiencia laboral</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/Novedad__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa las novedades que puede presentar un empleado, como incapacidad, vacaciones, licencia, en labor, otra.</description>
    <label>Novedad</label>
    <nameField>
        <displayFormat>NV-{0000}</displayFormat>
        <label>Nombre de Novedad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Novedades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Novedad__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la novedad esta activa o no</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Comentario__c.field-meta.xml
<CustomField>
    <fullName>Comentario__c</fullName>
    <description>Comentario opcional para la novedad</description>
    <label>Comentario</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Empleado__c.field-meta.xml
<CustomField>
    <fullName>Empleado__c</fullName>
    <description>Empleado que tendrá asociadas las novedades</description>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado Salesforce, Empleado E-volution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Novedades</relationshipLabel>
    <relationshipName>Novedades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_finalizacion__c</fullName>
    <description>Fecha de finalización de la novedad</description>
    <label>Fecha de finalización</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio de la novedad</description>
    <label>Fecha de inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Tipo_de_novedad__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_novedad__c</fullName>
    <description>Tipo de novedades que se pueden presentar</description>
    <label>Tipo de novedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incapacidad</fullName>
            </value>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Licencia</fullName>
            </value>
            <value>
                <fullName>Otra</fullName>
            </value>
            <value>
                <fullName>Asignacion Laboral</fullName>
                <label>Asignación Laboral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/schedulableNovedadTest.cls
@isTest
public class schedulableNovedadTest {
    
    @testSetup
    static void makeData(){
        Contact contacto = new Contact(lastName = 'Aguirre',disponibilidad__c = 'Disponible');
        insert contacto;
        contacto = [SELECT Id, lastName From Contact Limit 1];
        
        list<novedad__c> nuevasNovedades =new list<novedad__c>();
        for(integer i = 0; i < 9 ; i++){
            if(i<3){
                novedad__c novedad = new novedad__c();
                novedad.Fecha_de_inicio__c = date.today();
                novedad.Fecha_de_finalizacion__c = date.today().addDays(2);
                novedad.Tipo_de_novedad__c = 'Incapacidad';
                novedad.Empleado__c = contacto.Id;
                novedad.Activo__c = false;
                
                nuevasNovedades.add(novedad);
            }else if(i>2 && i <6){
                novedad__c novedad = new novedad__c();
                novedad.Fecha_de_inicio__c = date.today().addDays(2);
                novedad.Fecha_de_finalizacion__c = date.today().addDays(3);
                novedad.Tipo_de_novedad__c = 'Incapacidad';
                novedad.Empleado__c = contacto.Id;
                novedad.Activo__c = false;
                
                nuevasNovedades.add(novedad);
            }else{
                novedad__c novedad = new novedad__c();
                novedad.Fecha_de_inicio__c = date.today().addDays(-3);
                novedad.Fecha_de_finalizacion__c = date.today().addDays(3);
                novedad.Tipo_de_novedad__c = 'Incapacidad';
                novedad.Empleado__c = contacto.Id;
                novedad.Activo__c = false;
                
                nuevasNovedades.add(novedad);
            }
            
        }
        insert nuevasNovedades;
        list<Novedad__c> novedades3 = [select id, activo__c from Novedad__c];
        system.debug('makeup'+novedades3);
    }
    
    @isTest
    static void novedadActiva(){
        list<Novedad__c> novedades3 = [select id, activo__c from Novedad__c];
        system.assertEquals(9, novedades3.size());
        system.debug('antes del test'+novedades3);
        
        schedulableNovedad m = new schedulableNovedad();
        test.startTest();
        String sch = '0 0 1 * * ?';
        
        String jobId = System.schedule('testBasicScheduledApex',sch,new schedulableNovedad());      
        test.stopTest();
        
        list<Novedad__c> novedades2 = [select id, activo__c from Novedad__c where activo__c = true ];
        system.assertEquals(6, novedades2.size());
        system.debug('fuera de Test '+novedades2);
        
        list<Novedad__c> novedades5 = [select id, activo__c from novedad__c where activo__c = false];
        system.assertEquals(3, novedades5.size());
        
        list<Novedad__c> novedadesTrigger = [select id, activo__c, comentario__c FROM Novedad__c WHERE Fecha_de_inicio__c =: date.today()];
        system.assert(novedadesTrigger[0].comentario__c.contains('Activo'));
    }
    
    @isTest
    static void contactoNoDisponible(){
        Contact contactoActualizado = [select id, disponibilidad__c from contact limit 1];
        
        system.assertEquals('No Disponible', contactoActualizado.disponibilidad__c);
    }
    
    @isTest
    static void deleteUndeleteNovedad(){
        list<novedad__c> novedades = [select id from novedad__c];
        Id novedadBorrable = novedades[0].id;
        
        system.assertEquals(9, novedades.size());
        delete novedades[0];
        
        list<novedad__c> novedades1 = [select id from novedad__c];
        system.assertEquals(8, novedades1.size());
        
        novedad__c undeleteContact = new novedad__c(id= novedadBorrable);
        undelete undeleteContact;
        
         list<novedad__c> novedades2 = [select id from novedad__c];
        system.assertEquals(9, novedades2.size());
    }
}