force-app/main/default/objects/Contact/fields/Disponibilidad__c.field-meta.xml
<CustomField>
    <fullName>Disponibilidad__c</fullName>
    <description>especifica la disponibilidad de este empleado para una asignacion laboral</description>
    <label>Disponibilidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponible</fullName>
            </value>
            <value>
                <fullName>No Disponible</fullName>
            </value>
            <value>
                <fullName>Disponible Medio Tiempo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha en la que inicio en la empresa que registro como experiencia laboral</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/Novedad__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa las novedades que puede presentar un empleado, como incapacidad, vacaciones, licencia, en labor, otra.</description>
    <label>Novedad</label>
    <nameField>
        <displayFormat>NV-{0000}</displayFormat>
        <label>Nombre de Novedad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Novedades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Novedad__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la novedad esta activa o no</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Empleado__c.field-meta.xml
<CustomField>
    <fullName>Empleado__c</fullName>
    <description>Empleado que tendrá asociadas las novedades</description>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado Salesforce, Empleado E-volution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Novedades</relationshipLabel>
    <relationshipName>Novedades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_finalizacion__c</fullName>
    <description>Fecha de finalización de la novedad</description>
    <label>Fecha de finalización</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio de la novedad</description>
    <label>Fecha de inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Tipo_de_novedad__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_novedad__c</fullName>
    <description>Tipo de novedades que se pueden presentar</description>
    <label>Tipo de novedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incapacidad</fullName>
            </value>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Licencia</fullName>
            </value>
            <value>
                <fullName>Otra</fullName>
            </value>
            <value>
                <fullName>Asignacion Laboral</fullName>
                <label>Asignación Laboral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/schedulableContactoTest.cls
@isTest
public class schedulableContactoTest {

    @testSetup
    static void makeData(){
        contact contacto1 = new contact(lastName = 'Prueba sin Novedad', Disponibilidad__c = 'Disponible');
        insert contacto1;
        
        contact contacto2 = new contact(lastName = 'Prueba Con Novedad', Disponibilidad__c = 'Disponible');
        insert contacto2;
        
        novedad__c novedadNueva = new novedad__c(Activo__c = true,Fecha_de_inicio__c = date.today(), Fecha_de_finalizacion__c = date.today().addDays(2), Tipo_de_novedad__c ='Incapacidad', Empleado__c = contacto2.Id);
        insert novedadNueva;
    }
    
    @isTest
    public static void cambiarNoDisponible(){
        
        schedulableContacto m = new schedulableContacto();
        test.startTest();
        String sch = '0 0 2 * * ?';
        
        String jobId = System.schedule('testBasicScheduledApex',sch,new schedulableContacto());      
        test.stopTest();
        
        Contact contactoActualizado = [select id, Disponibilidad__c from contact where LastName = 'Prueba Con Novedad'];
        system.assertEquals('No Disponible', contactoActualizado.Disponibilidad__c);
    }
}