force-app/main/default/objects/Contact/fields/Disponibilidad__c.field-meta.xml
<CustomField>
    <fullName>Disponibilidad__c</fullName>
    <description>especifica la disponibilidad de este empleado para una asignacion laboral</description>
    <label>Disponibilidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponible</fullName>
            </value>
            <value>
                <fullName>No Disponible</fullName>
            </value>
            <value>
                <fullName>Disponible Medio Tiempo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Novedad__c/Novedad__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa las novedades que puede presentar un empleado, como incapacidad, vacaciones, licencia, en labor, otra.</description>
    <label>Novedad</label>
    <nameField>
        <displayFormat>NV-{0000}</displayFormat>
        <label>Nombre de Novedad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Novedades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Novedad__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la novedad esta activa o no</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Empleado__c.field-meta.xml
<CustomField>
    <fullName>Empleado__c</fullName>
    <description>Empleado que tendrá asociadas las novedades</description>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado Salesforce, Empleado E-volution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Novedades</relationshipLabel>
    <relationshipName>Novedades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/schedulableContacto.cls
public class schedulableContacto implements Schedulable{
    
    public void execute(SchedulableContext ctx){
        List<Contact> contactos = [select id, Disponibilidad__c from contact];
        set<id> idContact = new set<id>();
        for(contact contacto :contactos){
            idContact.add(contacto.Id);
        }
        list<Novedad__c> novedadesContacto = [select id, Activo__c, Empleado__c from Novedad__c where Empleado__c IN: idContact];
        List<Contact> contactoActualizable = new list<Contact>();
        for(contact contacto : contactos){
            Contact nuevoContacto = new contact(id = contacto.Id,Disponibilidad__c = 'Disponible');
            for(Novedad__c novedad : novedadesContacto){
                if(contacto.Id == novedad.Empleado__c){
                    if(novedad.Activo__c == true){
                        nuevoContacto.Disponibilidad__c = 'No Disponible';
                    }
                }
            }
            contactoActualizable.add(nuevoContacto);
        }
        
        try{
            update contactoActualizable;
        }catch(exception e){
            throw new ErrorException(e);
        }
    }
    
    public class ErrorException extends Exception{}
}