force-app/main/default/objects/Contact/fields/Disponibilidad__c.field-meta.xml
<CustomField>
    <fullName>Disponibilidad__c</fullName>
    <description>especifica la disponibilidad de este empleado para una asignacion laboral</description>
    <label>Disponibilidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponible</fullName>
            </value>
            <value>
                <fullName>No Disponible</fullName>
            </value>
            <value>
                <fullName>Disponible Medio Tiempo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha en la que inicio en la empresa que registro como experiencia laboral</description>
    <label>Fecha de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/Novedad__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa las novedades que puede presentar un empleado, como incapacidad, vacaciones, licencia, en labor, otra.</description>
    <label>Novedad</label>
    <nameField>
        <displayFormat>NV-{0000}</displayFormat>
        <label>Nombre de Novedad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Novedades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Novedad__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la novedad esta activa o no</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Comentario__c.field-meta.xml
<CustomField>
    <fullName>Comentario__c</fullName>
    <description>Comentario opcional para la novedad</description>
    <label>Comentario</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Empleado__c.field-meta.xml
<CustomField>
    <fullName>Empleado__c</fullName>
    <description>Empleado que tendrá asociadas las novedades</description>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado Salesforce, Empleado E-volution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Novedades</relationshipLabel>
    <relationshipName>Novedades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_finalizacion__c</fullName>
    <description>Fecha de finalización de la novedad</description>
    <label>Fecha de finalización</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Fecha_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_inicio__c</fullName>
    <description>Fecha de inicio de la novedad</description>
    <label>Fecha de inicio</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Jornada__c.field-meta.xml
<CustomField>
    <fullName>Jornada__c</fullName>
    <description>Define la jornada de la asignacion laboral en tiempo completo, medio tiempo AM, medio tiempo PM con el fin de realizar un mejor seguimiento</description>
    <label>Jornada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tiempo Completo</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Novedad__c/fields/Tipo_de_novedad__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_novedad__c</fullName>
    <description>Tipo de novedades que se pueden presentar</description>
    <label>Tipo de novedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incapacidad</fullName>
            </value>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Licencia</fullName>
            </value>
            <value>
                <fullName>Otra</fullName>
            </value>
            <value>
                <fullName>Asignacion Laboral</fullName>
                <label>Asignación Laboral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NovedadTriggerHandler.cls
public with sharing class NovedadTriggerHandler implements TriggerHandler{
    private boolean triggerIsExecuting;
    private integer triggerSize;
    public NovedadTriggerHandler(boolean triggerIsExecuting, integer triggerSize) {
        this.triggerIsExecuting = triggerIsExecuting;
        this.triggerSize = triggerSize;
    }
    
    public void beforeInsert(List<Novedad__c> newRecords) {
        activarNovedad(newRecords);
    }
    public void beforeUpdate(List<Novedad__c> oldRecords, List<Novedad__c> newRecords, Map<ID, sObject> oldRecordMap, Map<ID, sObject> newRecordMap){
        
    }
    public void beforeDelete(List<Novedad__c> oldRecords, Map<ID, sObject> oldRecordMap) {
        
    }
    public void afterInsert(List<Novedad__c> newRecords, Map<ID, sObject> newRecordMap) {
        actualizarContacto(newRecords);
    }
    public void afterUpdate(List<Novedad__c> oldRecords, List<Novedad__c> newRecords, Map<ID, sObject> oldRecordMap, Map<ID, sObject> newRecordMap) {
        //actualizarContacto(newRecords,oldRecords);
    }
    public void afterDelete(List<Novedad__c> oldRecords, Map<ID, sObject> oldRecordMap) {
        
    }
    public void afterUndelete(List<Novedad__c> newRecords, Map<ID, sObject> newRecordMap) {
        
    }
    public static void activarNovedad(List<novedad__c> novedades){
        if(test.isRunningTest()){
            system.debug('estoy en un test!');
            for(novedad__c novedad: novedades){
                if(date.today() <= novedad.Fecha_de_finalizacion__c && date.today() >= novedad.Fecha_de_inicio__c){
                    novedad.Comentario__c = 'Activo';
                }
            }
        }else{
            for(novedad__c novedad: novedades){
                if(date.today() <= novedad.Fecha_de_finalizacion__c && date.today() >= novedad.Fecha_de_inicio__c){
                    novedad.Activo__c = true;
                }
            }
        }
    }
    
    public static void actualizarContacto(list<Novedad__c> novedades){
        /*set<Id> contactNovedad = new set<Id>();
for(Novedad__c novedad: novedadesNew){
for(Novedad__c novedadOld: novedadesOld){
if(novedad.Id == novedadOld.Id){
if(novedad.Activo__c != novedadOld.Activo__c){
contactNovedad.add(novedad.Empleado__c);
}
}
}
}
list<Contact> contactosNovedades = [select id, Disponibilidad__c from Contact where ID IN: contactNovedad];
List<Novedad__c> novedadesContactos = [select id, Empleado__c, Activo__c  from Novedad__c where Empleado__c IN: contactNovedad];
list<Contact> contactoActualizable = new list<Contact>();
for(Contact contacto : contactosNovedades){
boolean novedadActiva = false;
Contact contactoActu = new Contact();
for(Novedad__c novedad : novedadesContactos){
while (novedadActiva == false){
if(contacto.Id == novedad.Empleado__c){
if(novedad.Activo__c == true){
novedadActiva = true;
}else{
contactoActu.Id = contacto.Id;
switch on novedad.Tipo_de_novedad__c {
when 'Asignacion Laboral' {		
switch on novedad.Jornada__c{
when 'Tiempo Completo'{
contactoActu.Disponibilidad__c = 'No Disponible'; 
}when 'AM','PM'{
contactoActu.Disponibilidad__c = 'Disponible Medio Tiempo'; 
}
}
}	
when 'Incapacidad','Vacaciones','Licencia','Otra'  {		
contactoActu.Disponibilidad__c = 'No Disponible';
}
}
}
}
}
}
if(novedadActiva == false){
contactoActualizable.add(contactoActu);
}
}
update contactoActualizable;*/
        
        set<Id> idEmpleado = new set<Id>();
        for(novedad__c novedad:novedades){
            idEmpleado.add(novedad.Empleado__c);
        }
        List<Contact> empleados = [select id, disponibilidad__c from contact where Id IN: idEmpleado];
        List<Contact> empleadoActualizable = new list<Contact>();
        set<Contact> registrosParaActualizar=new set<Contact>();
        for(novedad__c novedad: novedades){
            for(contact contacto : empleados){
                if(novedad.Empleado__c == contacto.Id){
                    if(date.today() <= novedad.Fecha_de_finalizacion__c && date.today() >= novedad.Fecha_de_inicio__c && contacto.Disponibilidad__c == 'Disponible'){
                        Contact newEmpleado = new Contact(Id = contacto.Id,Disponibilidad__c = 'No Disponible');
                        registrosParaActualizar.add(newEmpleado);
                    }
                }
            }
        }
        empleadoActualizable.addAll(registrosParaActualizar);
        update empleadoActualizable;
        
    }
}